export const FETCH_DATA = 'FETCH_DATA';
export const APPLY_CHANGE = 'APPLY_CHANGE';
export const SELECT_COLUMN = 'SELECT_COLUMN';
export const TOGGLE_SETTINGS = 'TOGGLE_SETTINGS';
export const FETCH_APP_NAME = 'FETCH_APP_NAME';
